export const ErrorCode = {
  VIDEO_DOWNLOAD_FAILED: 'VIDEO_DOWNLOAD_FAILED',
  VIDEO_INVALID_URL: 'VIDEO_INVALID_URL',
  VIDEO_TOO_LONG: 'VIDEO_TOO_LONG',
  TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
  TRANSCRIPTION_TIMEOUT: 'TRANSCRIPTION_TIMEOUT',
  GEMINI_ANALYSIS_FAILED: 'GEMINI_ANALYSIS_FAILED',
  GEMINI_RATE_LIMITED: 'GEMINI_RATE_LIMITED',
  FFMPEG_PROCESSING_FAILED: 'FFMPEG_PROCESSING_FAILED',
  FFMPEG_INVALID_TIMESTAMPS: 'FFMPEG_INVALID_TIMESTAMPS',
  CLEANUP_FAILED: 'CLEANUP_FAILED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
